### ISSUE TITLE
Fix broken links in documentation

### ISSUE THREAD

**Issue by AlistairDoswald** [PlaytikaOSS/pybandits#29]
Links to all local documentation in the README.md, for example https://playtikaresearch.github.io/pybandits/installation.html, are broken and result in a 404.

**Comment by adarmiento** [comment]
Hi @AlistairDoswald, @spiaz worked at this already, there's an open PR: https://github.com/PlaytikaOSS/pybandits/pull/28/files

https://playtikasearch has been replaced by https://playtikaoss

**Comment by AlistairDoswald** [comment]
Just saw this as well. I'll check the links and validated the PR if it all checks our.

**Comment by AlistairDoswald** [comment]
PR was incomplete. I suggested some changes.
